I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2820, in script
    diver "Help…help…please…"
Exception: Sayer 'diver' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2820, in script
    diver "Help…help…please…"
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/ethanearle/Downloads/Renpy/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'diver' is not defined.

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
CaveGame 1.0
Mon Dec 11 10:05:41 2023
